### ISSUE TITLE
Piped session hangs when using PipeExtensions.pipeSession

### ISSUE THREAD

**Issue by jeanp413** [microsoft/dev-tunnels-ssh#52]
Hang happens in `forwardSessionRequest`, also when piping a channel data gets corrupted somehow. 
Can repro this consistently on an app I'm writing:
- native ssh client connects to nodejs app
- nodejs app using dev-tunnels-ssh creates local ssh server
  - on new session creates a session (using websocket) to remote ssh server and pipes SSHServerSession to a SSHClientSession
- For data corrupted issue, native ssh client executes some shell script on remote machine but received output is corrupted

Already fixed locally, will create a PR and try to write unit tests than can reproduce this behavior.

**Comment by jasongin** [comment]
@jeanp413 Thanks for reporting the issue and contributing a fix!

I'm curious, how/where are you using the TypeScript SSH library? Is it an open-source project?

**Comment by jasongin** [comment]
I merged the fix. It should be published to npm as version `3.11.7` shortly.

**Comment by jeanp413** [comment]
> I'm curious, how/where are you using the TypeScript SSH library? Is it an open-source project?

It's just a vscode extension that connects to a remote machine using ssh over websocket

> I merged the fix. It should be published to npm as version 3.11.7 shortly.

Thanks :tada: :tada: :tada:
