### ISSUE TITLE
SshSession leak if static SshSessionConfiguration is used

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/dev-tunnels-ssh#77]
If `SshSession` is created with a static `SshSessionConfiguration`, e.g. `SshSessionConfiguration.NoSecurity`, it will be rooted by `ConfigurationChanged` event handler and will never be garbage collected.

Path to the root:
```
				Microsoft.DevTunnels.Ssh.SshSessionConfiguration [Static variable Microsoft.DevTunnels.Ssh.SshSessionConfiguration.NoSecurity]
			EventHandler<EventArgs>
		EventHandler<EventArgs>
	Microsoft.DevTunnels.Ssh.SshSession+<>c__DisplayClass11_0
Microsoft.DevTunnels.Ssh.SshSession
```

**Comment by jasongin** [comment]
Looks like `SshSession` needs to unsubscribe from the `ConfigurationChanged` event when disposed.

**Comment by jasongin** [comment]
PR: https://github.com/microsoft/dev-tunnels-ssh/pull/78
