### ISSUE TITLE
SshChannel leak via long living cancellation arg of OpenChannelAsync()

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/dev-tunnels-ssh#79]
`SshSession.OpenChannelAsync()` registers a callback on its `cancellation` argument like this:
``` csharp
if (cancellation.CanBeCanceled)
{
	cancellation.Register(() => completionSource.TrySetCanceled());
	cancellation.ThrowIfCancellationRequested();
}
```

The callback registration is never disposed of. 

If `OpenChannelAsync()` is successful, `completionSource` will reference the opened `SshChannel` and the `SshSession`. If the `cancellation` argument is long living, it'll root them after `OpenChannelAsync()` is done, potentially causing a memory leak.

There are several other places in C# SSH library with a similar pattern.

**Comment by jasongin** [comment]
Closing because this was fixed in #80
