### ISSUE TITLE
Why not BenchmarkDotNet?

### ISSUE THREAD

**Issue by WojciechNagorski** [microsoft/dev-tunnels-ssh#94]
Why this project do not use BenchmarkDotNet? Using a stopwatch is inappropriate.

https://github.com/microsoft/dev-tunnels-ssh/blob/ebaba8cd263ad18ed1de34cf301ef1a2ded82d04/bench/cs/Ssh.Benchmark/Benchmark.cs#L57

**Comment by jasongin** [comment]
These tests are measuring the duration of high-level end-to-end scenarios that take multiple seconds to run. A Stopwatch is perfectly adequate for that kind of measurement. I am familiar with BenchmarkDotNet and use it in other projects to measure performance of fast lower-level operations, but it's unnecessary here.
